// writeAddon.js
// Writes the results as a tiny WoW addon, "LoadoutPlannerData", that does
// nothing but define one global table. LoadoutPlanner reads that table.
//
// Why a separate addon: addons can't use the internet, but they CAN load
// Lua files from their folder. A separate folder means this script can
// replace it freely without touching LoadoutPlanner itself.

import { mkdir, writeFile, rename, rm, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

export const ADDON_NAME = 'LoadoutPlannerData';
const INTERFACE_VERSION = '120100'; // matches LoadoutPlanner.toc

/** A Lua string literal. Lua 5.1 accepts raw UTF-8, so only escape the specials. */
function luaString(text) {
  return '"' + String(text)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r') + '"';
}

/** Is this a valid Lua identifier (can be written as `key = ...`)? */
const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;
const LUA_KEYWORDS = new Set(['and', 'break', 'do', 'else', 'elseif', 'end', 'false', 'for', 'function',
  'if', 'in', 'local', 'nil', 'not', 'or', 'repeat', 'return', 'then', 'true', 'until', 'while']);

function luaKey(key) {
  if (typeof key === 'number' || /^\d+$/.test(key)) return `[${Number(key)}]`;
  if (IDENTIFIER.test(key) && !LUA_KEYWORDS.has(key)) return key;
  return `[${luaString(key)}]`;
}

/** Serialize a JS value (objects, arrays, strings, numbers, booleans) as Lua. */
export function toLua(value, indent = '') {
  if (value === null || value === undefined) return 'nil';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error('cannot write non-finite number to Lua');
    return String(value);
  }
  if (typeof value === 'string') return luaString(value);
  const inner = indent + '\t';
  if (Array.isArray(value)) {
    if (value.length === 0) return '{}';
    return '{\n' + value.map((item) => `${inner}${toLua(item, inner)},`).join('\n') + `\n${indent}}`;
  }
  const keys = Object.keys(value);
  if (keys.length === 0) return '{}';
  return '{\n' + keys.map((key) => `${inner}${luaKey(key)} = ${toLua(value[key], inner)},`).join('\n') + `\n${indent}}`;
}

/**
 * Write <outputDir>/LoadoutPlannerData/{LoadoutPlannerData.toc, Data.lua}.
 * Writes to a temporary folder first and swaps it in, so the game never
 * sees a half-written addon.
 */
export async function writeAddon(outputDir, data) {
  const finalDir = path.join(outputDir, ADDON_NAME);
  const tempDir = path.join(outputDir, `${ADDON_NAME}.tmp-${process.pid}`);
  await rm(tempDir, { recursive: true, force: true });
  await mkdir(tempDir, { recursive: true });

  const toc = [
    `## Interface: ${INTERFACE_VERSION}`,
    '## Title: LoadoutPlanner Data (Raider.IO)',
    `## Notes: Most-played talent builds from the Raider.IO API, generated ${data.generated}.`,
    '## Author: LoadoutPlannerSync',
    `## Version: ${data.generated.slice(0, 10)}`,
    '',
    'Data.lua',
    '',
  ].join('\n');

  const lua = [
    '-- Generated by LoadoutPlannerSync. Do not edit: it is replaced on every sync.',
    `-- Data: Raider.IO API (https://raider.io), ${data.generated}.`,
    `LoadoutPlannerData = ${toLua(data)}`,
    '',
  ].join('\n');

  await writeFile(path.join(tempDir, `${ADDON_NAME}.toc`), toc);
  await writeFile(path.join(tempDir, 'Data.lua'), lua);

  await rm(finalDir, { recursive: true, force: true });
  await rename(tempDir, finalDir);
  return finalDir;
}

// ---- Bundle mode: data shipped INSIDE LoadoutPlanner ------------------------

/** A hash of the builds themselves, ignoring timestamps and request counts. */
export function contentHash(bundle) {
  const strip = (data) => data && { mythic: data.mythic, raid: data.raid, season: data.season };
  const stable = JSON.stringify({ parses: strip(bundle.parses), raiderio: strip(bundle.raiderio) });
  return createHash('sha1').update(stable).digest('hex');
}

/**
 * Write <addonDir>/Data/Builtin.lua defining LoadoutPlannerBuiltin =
 * { parses = <data>, raiderio = <data> }. If the builds are the same as the
 * file already there (same content hash), the file is left untouched, so a
 * daily job only publishes a release when something really changed.
 * Returns { file, changed }.
 */
export async function writeBundle(addonDir, bundle) {
  const file = path.join(addonDir, 'Data', 'Builtin.lua');
  const hash = contentHash(bundle);
  try {
    const existing = await readFile(file, 'utf8');
    if (existing.includes(`-- content-hash: ${hash}`)) return { file, changed: false };
  } catch {
    // no file yet
  }
  const lua = [
    '-- Generated daily by LoadoutPlannerSync (GitHub Actions). Do not edit by hand.',
    '-- Sources: parses.gg (free to reuse) and, when enabled, the Raider.IO API.',
    `-- content-hash: ${hash}`,
    `LoadoutPlannerBuiltin = ${toLua(bundle)}`,
    '',
  ].join('\n');
  await mkdir(path.dirname(file), { recursive: true });
  const temp = `${file}.tmp-${process.pid}`;
  await writeFile(temp, lua);
  await rename(temp, file);
  return { file, changed: true };
}
